version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tmobile"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-85ttwp8yp0uw"
s3_prefix = "tmobile"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
