AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tmobile-api

  Sample SAM Template for tmobile-api

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables: 
        TABLE_NAME: TMobile
  Api:
    Cors:
      AllowMethods: "'POST, GET, OPTIONS'"
      AllowOrigin: "'*'"

Resources:
  TMobileBillDownloadUrlApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: tmobile/
      Handler: app.lambda_bill_get_download_url
      Runtime: python3.8
      Timeout: 90
      Events:
        TMobile:
          Type: Api 
          Properties:
            Path: /api/phone/links/bills/{yearMonth}
            Method: get
            Auth:
              ApiKeyRequired: true
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TMobileTable

  TMobileUsersApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: tmobile/
      Handler: app.lambda_users_handler
      Runtime: python3.8
      Timeout: 90
      Events:
        TMobile:
          Type: Api 
          Properties:
            Path: /api/phone/users
            Method: get
            Auth:
              ApiKeyRequired: true
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TMobileTable

  TMobileBillsApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: tmobile/
      Handler: app.lambda_bills_handler
      Runtime: python3.8
      Timeout: 90
      Events:
        TMobile:
          Type: Api 
          Properties:
            Path: /api/phone/bills
            Method: get
            Auth:
              ApiKeyRequired: true
    Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TMobileTable

  TMobileBillDetailsApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: tmobile/
      Handler: app.lambda_bill_details_handler
      Runtime: python3.8
      Timeout: 90
      Events:
        TMobile:
          Type: Api 
          Properties:
            Path: /api/phone/bills/{yearMonth}
            Method: get
            Auth:
              ApiKeyRequired: true
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TMobileTable
  
  TMobileUserRolesApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: tmobile/
      Handler: app.lambda_user_roles_handler
      Runtime: python3.8
      Timeout: 90
      Events:
        TMobile:
          Type: Api 
          Properties:
            Path: /api/phone/roles
            Method: get
            Auth:
              ApiKeyRequired: true
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TMobileTable

  TMobilePaymentsApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: tmobile/
      Handler: payments.lambda_payments_handler
      Runtime: python3.8
      Timeout: 90
      Events:
        TMobile:
          Type: Api 
          Properties:
            Path: /api/phone/payments
            Method: get
            Auth:
              ApiKeyRequired: true
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TMobileTable

  TMobilePaymentsByMonthApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: tmobile/
      Handler: payments.lambda_payments_byuser_handler
      Runtime: python3.8
      Timeout: 90
      Events:
        TMobile:
          Type: Api 
          Properties:
            Path: /api/phone/payments/user/{user}
            Method: get
            Auth:
              ApiKeyRequired: true
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TMobileTable

  TMobileTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TMobile
      AttributeDefinitions: 
        - AttributeName: Name
          AttributeType: S
        - AttributeName: Type
          AttributeType: S
      KeySchema: 
        - AttributeName: Name
          KeyType: HASH
        - AttributeName: Type
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  sairama-t-mobile:
    Type: AWS::S3::Bucket        