AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tmobile-api

  Sample SAM Template for tmobile-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables: 
        TABLE_NAME: TMobile

Resources:
  TMobileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tmobile/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 90
      Events:
        TMobile:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/phone/users
            Method: get
    Policies:
     - DynamoDBCrudPolicy:
        TableName: !Ref TMobileTable

TMobileTable:
  Type: AWS::Serverless::SimpleTable
  Properties:
    PrimaryKey: Name
    TableName: TMobile
    AttributeDefinitions: 
        - 
          AttributeName: "Name"
          AttributeType: "S"
        - 
          AttributeName: "Type"
          AttributeType: "S"
    KeySchema: 
        - 
          AttributeName: "Name"
          KeyType: "HASH"
        - 
          AttributeName: "Type"
          KeyType: "RANGE"

    ProvisionedThroughput: 
        ReadCapacityUnits: "2"
        WriteCapacityUnits: "2"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TMobileApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/phone/users"
  TMobileFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TMobileFunction.Arn
  TMobileFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TMobileFunctionRole.Arn
